export const DISPLAY_ALERT = 'DISPLAY_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const NEW_BOOKING_BEGIN = 'NEW_BOOKING_BEGIN';
export const NEW_BOOKING_SUCCESS = 'NEW_BOOKING_SUCCESS';
export const NEW_BOOKING_FAIL = 'NEW_BOOKING_FAIL';

export const GET_BOOKING_SUCCESS = 'GET_BOOKING_SUCCESS';
